// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUGjwi756WGGG6AGLgUH3LzC-9ijiKGI',
    appId: '1:516619520034:web:e8cb5e2985a57c8b55227b',
    messagingSenderId: '516619520034',
    projectId: 'testlaundry-b536a',
    authDomain: 'testlaundry-b536a.firebaseapp.com',
    storageBucket: 'testlaundry-b536a.appspot.com',
    measurementId: 'G-N0S06JJ98V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdqb5sMBJxPzBwfZFZeuoBrFv2mgI6ww',
    appId: '1:516619520034:android:4a20f952f0f2f13555227b',
    messagingSenderId: '516619520034',
    projectId: 'testlaundry-b536a',
    storageBucket: 'testlaundry-b536a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8MNVPbojT9opyoY72bSx5C-lcQf7tvKE',
    appId: '1:516619520034:ios:1092e7f30aec66e855227b',
    messagingSenderId: '516619520034',
    projectId: 'testlaundry-b536a',
    storageBucket: 'testlaundry-b536a.appspot.com',
    iosClientId: '516619520034-jqfd2581nmntueu6p5hag8pihpmd2sem.apps.googleusercontent.com',
    iosBundleId: 'com.fahim.flutter.testLundryAppLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8MNVPbojT9opyoY72bSx5C-lcQf7tvKE',
    appId: '1:516619520034:ios:1092e7f30aec66e855227b',
    messagingSenderId: '516619520034',
    projectId: 'testlaundry-b536a',
    storageBucket: 'testlaundry-b536a.appspot.com',
    iosClientId: '516619520034-jqfd2581nmntueu6p5hag8pihpmd2sem.apps.googleusercontent.com',
    iosBundleId: 'com.fahim.flutter.testLundryAppLearning',
  );
}
